# solar_forecasting_model.py
# Forecasting solar power generation from your existing sensor dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from datetime import timedelta

# 1️⃣ Load your dataset
df = pd.read_csv("dummy_dataset.csv")

# 2️⃣ Parse timestamps and sort
df["timestamp"] = pd.to_datetime(df["timestamp"])
df = df.sort_values(by=["unit_id", "timestamp"]).reset_index(drop=True)

# 3️⃣ Derive features from raw sensor data
# Power generated by the panel (Watts)
df["power_W"] = df["panel_voltage_V"] * df["panel_current_A"]

# Time-based features (useful for forecasting)
df["day_of_year"] = df["timestamp"].dt.dayofyear
df["hour"] = df["timestamp"].dt.hour

# Optional environmental interaction
df["temperature_effect"] = df["temperature_C"] - df["temperature_C"].mean()

# Target: next-hour power (forecasting one step ahead)
df["target_next_power_W"] = df.groupby("unit_id")["power_W"].shift(-1)

# Drop rows without target values (last rows per unit)
df = df.dropna().reset_index(drop=True)

# 4️⃣ Feature selection 
features = [
    "solar_irradiance_Wm2",
    "temperature_C",
    "panel_voltage_V",
    "panel_current_A",
    "battery_soc_pct",
    "day_of_year",
    "hour",
    "temperature_effect"
]
target = "target_next_power_W"

X = df[features]
y = df[target]

# 5️⃣ Split into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6️⃣ Train the model
model = RandomForestRegressor(n_estimators=150, random_state=42)
model.fit(X_train, y_train)

# 7️⃣ Evaluate model performance
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("✅ Model Evaluation:")
print(f"Mean Absolute Error: {mae:.2f} W")
print(f"R² Score: {r2:.3f}")

# 8️⃣ Forecast next 24 hours for each solar unit
future_forecasts = []
for unit in df["unit_id"].unique():
    latest_data = df[df["unit_id"] == unit].iloc[-24:].copy()
    future_times = [latest_data["timestamp"].iloc[-1] + timedelta(hours=i+1) for i in range(24)]

    X_future = latest_data[features].tail(24)
    y_future_pred = model.predict(X_future)

    forecast_df = pd.DataFrame({
        "unit_id": unit,
        "future_timestamp": future_times,
        "predicted_power_W": y_future_pred
    })
    future_forecasts.append(forecast_df)

forecast_all = pd.concat(future_forecasts, ignore_index=True)

# 9️⃣ Save forecast results
forecast_all.to_csv("aurion_forecast_results.csv", index=False)
print("\n📁 Forecast results saved as aurion_forecast_results.csv")

# 🔟 Visualize actual vs predicted (sample)
plt.figure(figsize=(10, 5))
plt.plot(y_test.values[:100], label="Actual Power", linewidth=2)
plt.plot(y_pred[:100], label="Predicted Power", linestyle="--")
plt.title("Actual vs Predicted Solar Power Output")
plt.xlabel("Sample Index")
plt.ylabel("Power (W)")
plt.legend()
plt.tight_layout()
plt.show()
